select  EMPLOYEE_ID, FIRST_NAME, LAST_NAME, MANAGER_ID from employees;

-- what is the first name and last name of manager Neena, or
-- Who is the Neena manger in this table ?
SELECT WORKERS.EMPLOYEE_ID, WORKERS.FIRST_NAME, WORKERS.LAST_NAME, WORKERS.MANAGER_ID,
       MANAGERS.EMPLOYEE_ID, MANAGERS.FIRST_NAME, MANAGERS.LAST_NAME
FROM EMPLOYEES WORKERS JOIN EMPLOYEES MANAGERS
ON WORKERS.MANAGER_ID = MANAGERS.EMPLOYEE_ID;

-- HOW CAN I SEE ALL EMPLOYEES EVEN IF THEY DON'T HAVE ANY MANAGER ?
SELECT WORKERS.EMPLOYEE_ID, WORKERS.FIRST_NAME, WORKERS.LAST_NAME, WORKERS.MANAGER_ID,
       MANAGERS.EMPLOYEE_ID, MANAGERS.FIRST_NAME, MANAGERS.LAST_NAME
FROM EMPLOYEES WORKERS left JOIN EMPLOYEES MANAGERS
                            ON WORKERS.MANAGER_ID = MANAGERS.EMPLOYEE_ID
order by 1 asc ;

















