SELECT FIRST_NAME, SALARY from EMPLOYEES
where SALARY > 3000
order by substr(FIRST_NAME, -3), SALARY desc ;

select DEPARTMENT_NAME, count(*) from DEPARTMENTS D
left join EMPLOYEES E on D.DEPARTMENT_ID = E.DEPARTMENT_ID
group by DEPARTMENT_NAME;

select DEPARTMENT_NAME, FIRST_NAME, EMPLOYEE_ID from DEPARTMENTS
left join EMPLOYEES E on DEPARTMENTS.DEPARTMENT_ID = E.DEPARTMENT_ID;

select DEPARTMENT_NAME, FIRST_NAME, LAST_NAME, SALARY  from DEPARTMENTS
full join EMPLOYEES E on DEPARTMENTS.DEPARTMENT_ID = E.DEPARTMENT_ID
where DEPARTMENT_NAME ='Treasury';

select FIRST_NAME, LAST_NAME, DEPARTMENT_NAME, E.DEPARTMENT_ID from EMPLOYEES E
left outer join DEPARTMENTS D on E.EMPLOYEE_ID = D.DEPARTMENT_ID;

select DEPARTMENT_NAME, count(FIRST_NAME) from EMPLOYEES E
left join DEPARTMENTS D on E.EMPLOYEE_ID = D.DEPARTMENT_ID
group by DEPARTMENT_NAME;

select FIRST_NAME, LAST_NAME, DEPARTMENT_NAME, E.DEPARTMENT_ID from EMPLOYEES E
left outer join DEPARTMENTS D on E.EMPLOYEE_ID = D.DEPARTMENT_ID
where FIRST_NAME = 'Matthew';

select FIRST_NAME, LAST_NAME, DEPARTMENT_NAME, E.DEPARTMENT_ID from departments d full join employees e
on d.DEPARTMENT_ID = e.DEPARTMENT_ID
where FIRST_NAME = 'Matthew';

select DEPARTMENT_NAME, FIRST_NAME from DEPARTMENTS D
full join EMPLOYEES E on D.DEPARTMENT_ID = E.DEPARTMENT_ID;

select E1.EMPLOYEE_ID, E1.FIRST_NAME from EMPLOYEES E1
join EMPLOYEES E2 on E1.MANAGER_ID = E2.EMPLOYEE_ID
where E1.SALARY > E2.SALARY;